version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: local_mongodb
    restart: none
    ports:
      - "27015:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=suadmin
      - MONGO_INITDB_ROOT_PASSWORD=secretpwd
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: